//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (table_name = "account")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , pub money : i32 , pub locked_money : i32 , pub created_at : DateTimeWithTimeZone , pub updated_at : DateTimeWithTimeZone , pub removed_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::cert::Entity")] Cert , # [sea_orm (has_many = "super::dictator::Entity")] Dictator , # [sea_orm (has_many = "super::identity::Entity")] Identity , # [sea_orm (has_many = "super::post::Entity")] Post , # [sea_orm (has_one = "super::profile::Entity")] Profile , # [sea_orm (has_many = "super::proposal::Entity")] Proposal , # [sea_orm (has_many = "super::proposal_comment::Entity")] ProposalComment , # [sea_orm (has_many = "super::ruling::Entity")] Ruling , # [sea_orm (has_many = "super::thread::Entity")] Thread , # [sea_orm (has_many = "super::thread_comment::Entity")] ThreadComment , # [sea_orm (has_many = "super::user_badge::Entity")] UserBadge , # [sea_orm (has_many = "super::user_inventory::Entity")] UserInventory , # [sea_orm (has_many = "super::vote::Entity")] Vote , }

impl Related < super :: cert :: Entity > for Entity { fn to () -> RelationDef { Relation :: Cert . def () } }

impl Related < super :: dictator :: Entity > for Entity { fn to () -> RelationDef { Relation :: Dictator . def () } }

impl Related < super :: identity :: Entity > for Entity { fn to () -> RelationDef { Relation :: Identity . def () } }

impl Related < super :: post :: Entity > for Entity { fn to () -> RelationDef { Relation :: Post . def () } }

impl Related < super :: profile :: Entity > for Entity { fn to () -> RelationDef { Relation :: Profile . def () } }

impl Related < super :: proposal :: Entity > for Entity { fn to () -> RelationDef { Relation :: Proposal . def () } }

impl Related < super :: proposal_comment :: Entity > for Entity { fn to () -> RelationDef { Relation :: ProposalComment . def () } }

impl Related < super :: ruling :: Entity > for Entity { fn to () -> RelationDef { Relation :: Ruling . def () } }

impl Related < super :: thread :: Entity > for Entity { fn to () -> RelationDef { Relation :: Thread . def () } }

impl Related < super :: thread_comment :: Entity > for Entity { fn to () -> RelationDef { Relation :: ThreadComment . def () } }

impl Related < super :: user_badge :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserBadge . def () } }

impl Related < super :: user_inventory :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserInventory . def () } }

impl Related < super :: vote :: Entity > for Entity { fn to () -> RelationDef { Relation :: Vote . def () } }

impl Related < super :: badge :: Entity > for Entity { fn to () -> RelationDef { super :: user_badge :: Relation :: Badge . def () } fn via () -> Option < RelationDef > { Some (super :: user_badge :: Relation :: Account . def () . rev ()) } }

impl Related < super :: shop_item :: Entity > for Entity { fn to () -> RelationDef { super :: user_inventory :: Relation :: ShopItem . def () } fn via () -> Option < RelationDef > { Some (super :: user_inventory :: Relation :: Account . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }