//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (table_name = "proposal_comment")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , pub author_id : Uuid , # [sea_orm (column_type = "Text" , nullable)] pub content : Option < String > , pub vote_id : Option < Uuid > , pub created_at : DateTimeWithTimeZone , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::account::Entity" , from = "Column::AuthorId" , to = "super::account::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Account , # [sea_orm (belongs_to = "super::vote::Entity" , from = "Column::VoteId" , to = "super::vote::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Vote , }

impl Related < super :: account :: Entity > for Entity { fn to () -> RelationDef { Relation :: Account . def () } }

impl Related < super :: vote :: Entity > for Entity { fn to () -> RelationDef { Relation :: Vote . def () } }

impl ActiveModelBehavior for ActiveModel { }