packages:
  - packages/**

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@suites/di.nestjs': true
  '@suites/doubles.vitest': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
