// This file is auto-generated by @hey-api/openapi-ts

export const LoginDTOSchema = {
    type: 'object',
    properties: {
        identType: {
            type: 'string',
            description: '标识类型'
        },
        identValue: {
            type: 'string',
            description: '标识值'
        },
        credentialType: {
            type: 'string',
            description: '凭证类型'
        },
        credentialValue: {
            type: 'string',
            description: '凭证值'
        }
    },
    required: [
        'identType',
        'identValue',
        'credentialType',
        'credentialValue'
    ]
} as const;

export const TokenPairSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string',
            description: '访问令牌, 用于访问受到保护的资源'
        },
        refreshToken: {
            type: 'string',
            description: '刷新令牌, 用于刷新访问令牌'
        },
        accessTokenTTL: {
            type: 'number',
            description: '访问令牌有效期 (秒)'
        },
        refreshTokenTTL: {
            type: 'number',
            description: '刷新令牌有效期 (秒)'
        }
    },
    required: [
        'accessToken',
        'refreshToken',
        'accessTokenTTL',
        'refreshTokenTTL'
    ]
} as const;

export const RegisterProfileSchema = {
    type: 'object',
    properties: {
        nick: {
            type: 'string',
            description: '昵称'
        },
        bio: {
            type: 'string',
            description: '个人简介'
        }
    },
    required: [
        'nick',
        'bio'
    ]
} as const;

export const RegisterRequestSchema = {
    type: 'object',
    properties: {
        identType: {
            type: 'string',
            description: '标识类型'
        },
        identValue: {
            type: 'string',
            description: '标识值'
        },
        credentialType: {
            type: 'string',
            description: '凭证类型'
        },
        credentialValue: {
            type: 'string',
            description: '凭证值'
        },
        profile: {
            description: '个人信息',
            allOf: [
                {
                    $ref: '#/components/schemas/RegisterProfile'
                }
            ]
        },
        verificationCode: {
            type: 'string',
            description: '验证码'
        }
    },
    required: [
        'identType',
        'identValue',
        'credentialType',
        'credentialValue',
        'profile'
    ]
} as const;

export const RegisterResponseSchema = {
    type: 'object',
    properties: {
        accountId: {
            type: 'object',
            description: '账号ID'
        }
    },
    required: [
        'accountId'
    ]
} as const;

export const RefreshTokenDTOSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string',
            description: '刷新令牌'
        }
    },
    required: [
        'token'
    ]
} as const;

export const PaginationDataSchema = {
    type: 'object',
    properties: {
        data: {
            description: '数据列表',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        total: {
            type: 'number',
            description: '总条数',
            default: 0
        }
    },
    required: [
        'data',
        'total'
    ]
} as const;

export const CategoryInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'object',
            description: '分类ID',
            example: '123-4567890'
        },
        name: {
            type: 'string',
            description: '分类名称',
            example: '技术分类'
        },
        icon: {
            type: 'string',
            description: '分类图标',
            example: 'icon-123'
        },
        color: {
            type: 'string',
            description: '分类颜色',
            example: '#000000'
        },
        createdAt: {
            type: 'string',
            description: '创建时间',
            example: '2023-01-01T00:00:00Z'
        },
        pined: {
            type: 'boolean',
            description: '是否置顶',
            example: true
        }
    },
    required: [
        'id',
        'name',
        'icon',
        'color',
        'createdAt',
        'pined'
    ]
} as const;

export const CreateCategoryRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: '分类名称'
        },
        color: {
            type: 'string',
            description: '分类颜色, 十六进制色彩值',
            example: '#FF0000'
        },
        icon: {
            type: 'string',
            description: '分类图标, 图标class'
        },
        pin: {
            type: 'boolean',
            description: '是否置顶',
            example: true
        }
    },
    required: [
        'name'
    ]
} as const;

export const UpdateCategoryRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: '分类名称'
        },
        color: {
            type: 'string',
            description: '分类颜色, 十六进制色彩值',
            example: '#FF0000'
        },
        icon: {
            type: 'string',
            description: '分类图标, 图标class'
        },
        pin: {
            type: 'boolean',
            description: '是否置顶',
            example: true
        }
    }
} as const;

export const RemoveCategoryResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: [
        'id'
    ]
} as const;

export const ReplyAuthorSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'object',
            description: '回复作者ID'
        },
        nick: {
            type: 'string',
            description: '回复作者昵称'
        }
    },
    required: [
        'id',
        'nick'
    ]
} as const;

export const ReplyItemSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'object',
            description: '回复ID'
        },
        content: {
            type: 'string',
            description: '回复内容'
        },
        author: {
            description: '回复作者',
            allOf: [
                {
                    $ref: '#/components/schemas/ReplyAuthor'
                }
            ]
        },
        createdAt: {
            type: 'string',
            description: '回复创建时间'
        }
    },
    required: [
        'id',
        'content',
        'author',
        'createdAt'
    ]
} as const;

export const TopicAuthorSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: '主题作者ID'
        },
        nick: {
            type: 'string',
            description: '主题作者昵称'
        }
    },
    required: [
        'id',
        'nick'
    ]
} as const;

export const TopicInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: '主题ID'
        },
        title: {
            type: 'string',
            description: '主题标题'
        },
        content: {
            type: 'string',
            description: '主题内容'
        },
        author: {
            description: '主题作者',
            allOf: [
                {
                    $ref: '#/components/schemas/TopicAuthor'
                }
            ]
        },
        createdAt: {
            type: 'string',
            description: '主题创建时间'
        },
        pinned: {
            type: 'boolean',
            description: '主题是否置顶'
        },
        replyTotal: {
            type: 'number',
            description: '主题回复总数'
        }
    },
    required: [
        'id',
        'title',
        'content',
        'author',
        'createdAt',
        'pinned',
        'replyTotal'
    ]
} as const;

export const CreateReplyDtoSchema = {
    type: 'object',
    properties: {
        content: {
            type: 'string',
            description: '回复内容'
        }
    },
    required: [
        'content'
    ]
} as const;

export const ReplyInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'object',
            description: '回复ID'
        },
        content: {
            type: 'string',
            description: '回复内容'
        },
        author: {
            description: '回复作者',
            allOf: [
                {
                    $ref: '#/components/schemas/ReplyAuthor'
                }
            ]
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            description: '回复创建时间'
        }
    },
    required: [
        'id',
        'content',
        'author',
        'createdAt'
    ]
} as const;

export const CreateTopicDtoSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: '主题标题'
        },
        content: {
            type: 'string',
            description: '主题内容'
        },
        pinned: {
            type: 'boolean',
            description: '是否置顶'
        }
    },
    required: [
        'title',
        'content',
        'pinned'
    ]
} as const;

export const UpdateTopicDtoSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: '主题标题'
        },
        content: {
            type: 'string',
            description: '主题内容'
        },
        pinned: {
            type: 'boolean',
            description: '是否置顶'
        },
        categoryId: {
            type: 'object',
            description: '分类ID'
        }
    },
    required: [
        'title',
        'content',
        'pinned',
        'categoryId'
    ]
} as const;

export const UpdateTopicResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: '主题ID'
        }
    },
    required: [
        'id'
    ]
} as const;

export const ProfileInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'object',
            description: '用户ID'
        },
        nick: {
            type: 'string',
            description: '昵称'
        },
        bio: {
            type: 'string',
            description: '个人简介'
        }
    },
    required: [
        'id',
        'nick'
    ]
} as const;

export const TopicCategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: '分类ID'
        },
        name: {
            type: 'string',
            description: '分类名称'
        },
        color: {
            type: 'string',
            description: '分类颜色'
        }
    },
    required: [
        'id',
        'name',
        'color'
    ]
} as const;

export const ProfileTopicInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: '主题ID'
        },
        title: {
            type: 'string',
            description: '主题标题'
        },
        content: {
            type: 'string',
            description: '主题内容'
        },
        createdAt: {
            type: 'string',
            description: '创建时间'
        },
        category: {
            description: '分类',
            allOf: [
                {
                    $ref: '#/components/schemas/TopicCategory'
                }
            ]
        },
        repliesTotal: {
            type: 'number',
            description: '回复总数'
        }
    },
    required: [
        'id',
        'title',
        'content',
        'createdAt',
        'category',
        'repliesTotal'
    ]
} as const;

export const UpdateProfileSchema = {
    type: 'object',
    properties: {
        nick: {
            type: 'string',
            description: '昵称'
        },
        bio: {
            type: 'string',
            description: '个人简介'
        }
    },
    required: [
        'nick',
        'bio'
    ]
} as const;

export const HttpPresentationErrorSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            description: '错误 message',
            example: '错误信息'
        },
        statusCode: {
            type: 'number',
            description: '错误状态码',
            example: 400
        },
        details: {
            type: 'object',
            description: '错误详情',
            example: {
                id: 123456
            }
        }
    },
    required: [
        'message',
        'statusCode',
        'details'
    ]
} as const;
