// This file is auto-generated by @hey-api/openapi-ts

export const GetProfileResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'Account ID'
        },
        username: {
            type: 'string'
        },
        bio: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        }
    },
    required: [
        'id',
        'username',
        'bio',
        'avatar'
    ]
} as const;

export const UpdateProfileDTOSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        bio: {
            type: 'string'
        }
    },
    required: [
        'username',
        'bio'
    ]
} as const;

export const UpdateProfileResponseSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        bio: {
            type: 'string'
        }
    },
    required: [
        'account_id',
        'username',
        'bio'
    ]
} as const;

export const RegisterDTOSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            example: 'Jack'
        },
        password: {
            type: 'string',
            example: 'example'
        },
        ident_type: {
            type: 'string',
            enum: [
                'Email'
            ]
        },
        ident_value: {
            type: 'string',
            example: 'example@example.org'
        },
        captcha: {
            type: 'string',
            description: 'The mail / sms captcha.'
        },
        invite_code: {
            type: 'string',
            description: 'iff enable_invite flag true will required'
        }
    },
    required: [
        'username',
        'password',
        'ident_type',
        'ident_value',
        'captcha',
        'invite_code'
    ]
} as const;

export const CreateAccountResponseSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        }
    },
    required: [
        'account_id'
    ]
} as const;

export const RemoveAccountResponseSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        }
    },
    required: [
        'account_id'
    ]
} as const;

export const ResetPasswordDTOSchema = {
    type: 'object',
    properties: {
        ident_value: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        mfa_code: {
            type: 'string'
        }
    },
    required: [
        'ident_value',
        'password',
        'mfa_code'
    ]
} as const;

export const UpdatePasswordSchema = {
    type: 'object',
    properties: {}
} as const;

export const LoginDTOSchema = {
    type: 'object',
    properties: {
        ident_type: {
            type: 'string',
            enum: [
                'Email'
            ]
        },
        ident_value: {
            type: 'string'
        },
        cert_value: {
            type: 'string'
        }
    },
    required: [
        'ident_type',
        'ident_value',
        'cert_value'
    ]
} as const;

export const LoginResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string',
            description: 'JWT,TTL: 15 Minutes. Used for accessing protected resources.'
        },
        refreshToken: {
            type: 'string',
            description: 'JWT, TTL: 1 Day. Used to request `/auth/refresh` refresh AccessToken'
        }
    },
    required: [
        'accessToken',
        'refreshToken'
    ]
} as const;
