// This file is auto-generated by @hey-api/openapi-ts

export const GetProfileResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'Account ID'
        },
        username: {
            type: 'string'
        },
        bio: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        }
    },
    required: [
        'id',
        'username',
        'bio',
        'avatar'
    ]
} as const;

export const UpdateProfileDTOSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        bio: {
            type: 'string'
        }
    },
    required: [
        'username',
        'bio'
    ]
} as const;

export const UpdateProfileResponseSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        bio: {
            type: 'string'
        }
    },
    required: [
        'account_id',
        'username',
        'bio'
    ]
} as const;

export const RegisterDTOSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            example: 'Jack'
        },
        password: {
            type: 'string',
            example: 'example'
        },
        ident_type: {
            type: 'string',
            enum: [
                'Email'
            ]
        },
        ident_value: {
            type: 'string',
            example: 'example@example.org'
        },
        captcha: {
            type: 'string',
            description: 'The mail / sms captcha.'
        },
        invite_code: {
            type: 'string',
            description: 'iff enable_invite flag true will required'
        }
    },
    required: [
        'username',
        'password',
        'ident_type',
        'ident_value',
        'captcha',
        'invite_code'
    ]
} as const;

export const CreateAccountResponseSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        }
    },
    required: [
        'account_id'
    ]
} as const;

export const RemoveAccountResponseSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        }
    },
    required: [
        'account_id'
    ]
} as const;

export const ResetPasswordDTOSchema = {
    type: 'object',
    properties: {
        ident_value: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        mfa_code: {
            type: 'string'
        }
    },
    required: [
        'ident_value',
        'password',
        'mfa_code'
    ]
} as const;

export const UpdatePasswordSchema = {
    type: 'object',
    properties: {}
} as const;

export const LoginDTOSchema = {
    type: 'object',
    properties: {
        ident_type: {
            type: 'string',
            enum: [
                'Email'
            ]
        },
        ident_value: {
            type: 'string'
        },
        cert_value: {
            type: 'string'
        }
    },
    required: [
        'ident_type',
        'ident_value',
        'cert_value'
    ]
} as const;

export const LoginResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string',
            description: 'JWT,TTL: 15 Minutes. Used for accessing protected resources.'
        },
        refreshToken: {
            type: 'string',
            description: 'JWT, TTL: 1 Day. Used to request `/auth/refresh` refresh AccessToken'
        }
    },
    required: [
        'accessToken',
        'refreshToken'
    ]
} as const;

export const CreatePostDTOSchema = {
    type: 'object',
    properties: {
        categoryId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        }
    },
    required: [
        'categoryId',
        'title',
        'content'
    ]
} as const;

export const CreatePostResponseSchema = {
    type: 'object',
    properties: {
        postId: {
            type: 'string'
        }
    },
    required: [
        'postId'
    ]
} as const;

export const AuthorSummarySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        }
    },
    required: [
        'id',
        'name'
    ]
} as const;

export const PostSummarySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        author: {
            $ref: '#/components/schemas/AuthorSummary'
        }
    },
    required: [
        'id',
        'title',
        'content',
        'author'
    ]
} as const;

export const HiddenPostDTOSchema = {
    type: 'object',
    properties: {}
} as const;

export const HiddenPostResponseSchema = {
    type: 'object',
    properties: {}
} as const;

export const CursorPaginationSchema = {
    type: 'object',
    properties: {
        cursor: {
            type: 'string'
        },
        data: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        total: {
            type: 'number'
        }
    },
    required: [
        'cursor',
        'data',
        'total'
    ]
} as const;

export const CreateCategoryDTOSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        parent: {
            type: 'string'
        }
    },
    required: [
        'name',
        'parent'
    ]
} as const;

export const CreateCategoryResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        hasChildren: {
            type: 'boolean'
        },
        parent: {
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'hasChildren',
        'parent'
    ]
} as const;

export const UpdateCategoryResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: [
        'id'
    ]
} as const;

export const UpdateCategoryDTOSchema = {
    type: 'object',
    properties: {
        parent: {
            type: 'object'
        }
    },
    required: [
        'parent'
    ]
} as const;

export const CategorySummarySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        parentId: {
            type: 'object'
        },
        hasChildren: {
            type: 'boolean'
        }
    },
    required: [
        'id',
        'name',
        'parentId',
        'hasChildren'
    ]
} as const;
