// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import { createReplyResponseTransformer, removeReplyResponseTransformer } from './transformers.gen';
import type { CreateCategoryData, CreateCategoryResponses, CreateReplyData, CreateReplyResponses, CreateTopicData, CreateTopicResponses, FindCategoryData, FindCategoryResponses, GetProfileData, GetProfileResponses, GetPublishedTopicData, GetPublishedTopicResponses, ListCategoryData, ListCategoryResponses, ListReplyData, ListReplyResponses, ListTopicData, ListTopicResponses, LoginData, LoginResponses, RecoverCategoryData, RecoverCategoryResponses, RefreshTokenData, RefreshTokenResponses, RegisterData, RegisterResponses, RemoveCategoryData, RemoveCategoryResponses, RemoveReplyData, RemoveReplyResponses, RemoveTopicData, RemoveTopicResponses, UpdateCategoryData, UpdateCategoryResponses, UpdateProfileData, UpdateProfileResponses, UpdateTopicData, UpdateTopicResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * 登陆账号, 并且签发一个新的令牌对
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 注册账号
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获得一个新的令牌对
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>): RequestResult<RefreshTokenResponses, unknown, ThrowOnError> => (options.client ?? client).post<RefreshTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/refresh-token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取分类列表
 */
export const listCategory = <ThrowOnError extends boolean = false>(options: Options<ListCategoryData, ThrowOnError>): RequestResult<ListCategoryResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListCategoryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/category',
    ...options
});

/**
 * 创建分类
 */
export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>): RequestResult<CreateCategoryResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateCategoryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/category',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除分类
 */
export const removeCategory = <ThrowOnError extends boolean = false>(options: Options<RemoveCategoryData, ThrowOnError>): RequestResult<RemoveCategoryResponses, unknown, ThrowOnError> => (options.client ?? client).delete<RemoveCategoryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/category/{id}',
    ...options
});

/**
 * 获取分类详情
 */
export const findCategory = <ThrowOnError extends boolean = false>(options: Options<FindCategoryData, ThrowOnError>): RequestResult<FindCategoryResponses, unknown, ThrowOnError> => (options.client ?? client).get<FindCategoryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/category/{id}',
    ...options
});

/**
 * 更新分类
 */
export const updateCategory = <ThrowOnError extends boolean = false>(options: Options<UpdateCategoryData, ThrowOnError>): RequestResult<UpdateCategoryResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UpdateCategoryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/category/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 恢复分类
 */
export const recoverCategory = <ThrowOnError extends boolean = false>(options: Options<RecoverCategoryData, ThrowOnError>): RequestResult<RecoverCategoryResponses, unknown, ThrowOnError> => (options.client ?? client).patch<RecoverCategoryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/category/recover/{id}',
    ...options
});

/**
 * 获取回复列表
 */
export const listReply = <ThrowOnError extends boolean = false>(options: Options<ListReplyData, ThrowOnError>): RequestResult<ListReplyResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListReplyResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/topic/replies/{topicId}',
    ...options
});

/**
 * 创建回复
 */
export const createReply = <ThrowOnError extends boolean = false>(options: Options<CreateReplyData, ThrowOnError>): RequestResult<CreateReplyResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateReplyResponses, unknown, ThrowOnError>({
    responseTransformer: createReplyResponseTransformer,
    responseType: 'json',
    url: '/topic/replies/{topicId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取主题列表
 */
export const listTopic = <ThrowOnError extends boolean = false>(options: Options<ListTopicData, ThrowOnError>): RequestResult<ListTopicResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListTopicResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/topic/{categoryId}',
    ...options
});

/**
 * 创建主题
 */
export const createTopic = <ThrowOnError extends boolean = false>(options: Options<CreateTopicData, ThrowOnError>): RequestResult<CreateTopicResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateTopicResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/topic/{categoryId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除回复
 */
export const removeReply = <ThrowOnError extends boolean = false>(options: Options<RemoveReplyData, ThrowOnError>): RequestResult<RemoveReplyResponses, unknown, ThrowOnError> => (options.client ?? client).delete<RemoveReplyResponses, unknown, ThrowOnError>({
    responseTransformer: removeReplyResponseTransformer,
    responseType: 'json',
    url: '/topic/replies/{replyId}',
    ...options
});

/**
 * 删除主题
 */
export const removeTopic = <ThrowOnError extends boolean = false>(options: Options<RemoveTopicData, ThrowOnError>): RequestResult<RemoveTopicResponses, unknown, ThrowOnError> => (options.client ?? client).delete<RemoveTopicResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/topic/{topicId}',
    ...options
});

/**
 * 更新主题
 */
export const updateTopic = <ThrowOnError extends boolean = false>(options: Options<UpdateTopicData, ThrowOnError>): RequestResult<UpdateTopicResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UpdateTopicResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/topic/{topicId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 通过Account ID获取用户信息
 *
 * 根据Account ID获取用户信息
 */
export const getProfile = <ThrowOnError extends boolean = false>(options: Options<GetProfileData, ThrowOnError>): RequestResult<GetProfileResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetProfileResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/profile/{id}',
    ...options
});

/**
 * 通过Account ID获取用户发布的主题
 *
 * 根据Account ID获取用户发布的主题
 */
export const getPublishedTopic = <ThrowOnError extends boolean = false>(options: Options<GetPublishedTopicData, ThrowOnError>): RequestResult<GetPublishedTopicResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPublishedTopicResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/profile/{id}/published-topic',
    ...options
});

/**
 * 更新用户信息
 */
export const updateProfile = <ThrowOnError extends boolean = false>(options: Options<UpdateProfileData, ThrowOnError>): RequestResult<UpdateProfileResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UpdateProfileResponses, unknown, ThrowOnError>({
    url: '/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
