// This file is auto-generated by @hey-api/openapi-ts

import type { CreateReplyResponse, GetBdRecordListResponse, GetBdRecordResponse, GetSelfRecordResponse, ListProposalItemsResponse, ProposalControllerFindProposalResponse, RemoveReplyResponse } from './types.gen';

const replyInfoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const createReplyResponseTransformer = async (data: any): Promise<CreateReplyResponse> => {
    data = replyInfoSchemaResponseTransformer(data);
    return data;
};

export const removeReplyResponseTransformer = async (data: any): Promise<RemoveReplyResponse> => {
    data = replyInfoSchemaResponseTransformer(data);
    return data;
};

const listProposalItemSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const listProposalItemsResponseTransformer = async (data: any): Promise<ListProposalItemsResponse> => {
    if (data.items) {
        data.items = data.items.map((item: any) => listProposalItemSchemaResponseTransformer(item));
    }
    return data;
};

export const proposalControllerFindProposalResponseTransformer = async (data: any): Promise<ProposalControllerFindProposalResponse> => {
    data = listProposalItemSchemaResponseTransformer(data);
    return data;
};

const governanceMemberInfoSchemaResponseTransformer = (data: any) => {
    data.startedAt = new Date(data.startedAt);
    data.endedAt = new Date(data.endedAt);
    return data;
};

export const getSelfRecordResponseTransformer = async (data: any): Promise<GetSelfRecordResponse> => {
    data = governanceMemberInfoSchemaResponseTransformer(data);
    return data;
};

export const getBdRecordResponseTransformer = async (data: any): Promise<GetBdRecordResponse> => {
    data = governanceMemberInfoSchemaResponseTransformer(data);
    return data;
};

export const getBdRecordListResponseTransformer = async (data: any): Promise<GetBdRecordListResponse> => {
    if (data.items) {
        data.items = data.items.map((item: any) => governanceMemberInfoSchemaResponseTransformer(item));
    }
    return data;
};
