// This file is auto-generated by @hey-api/openapi-ts

import type { CreateReplyResponse, ListProposalItemsResponse, ProposalControllerFindProposalResponse, RemoveReplyResponse } from './types.gen';

const replyInfoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const createReplyResponseTransformer = async (data: any): Promise<CreateReplyResponse> => {
    data = replyInfoSchemaResponseTransformer(data);
    return data;
};

export const removeReplyResponseTransformer = async (data: any): Promise<RemoveReplyResponse> => {
    data = replyInfoSchemaResponseTransformer(data);
    return data;
};

const listProposalItemSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const listProposalItemsResponseTransformer = async (data: any): Promise<ListProposalItemsResponse> => {
    if (data.data) {
        data.data = data.data.map((item: any) => listProposalItemSchemaResponseTransformer(item));
    }
    return data;
};

export const proposalControllerFindProposalResponseTransformer = async (data: any): Promise<ProposalControllerFindProposalResponse> => {
    data = listProposalItemSchemaResponseTransformer(data);
    return data;
};
