// This file is auto-generated by @hey-api/openapi-ts

import type { CreateReplyResponse, RemoveReplyResponse } from './types.gen';

const replyInfoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const createReplyResponseTransformer = async (data: any): Promise<CreateReplyResponse> => {
    data = replyInfoSchemaResponseTransformer(data);
    return data;
};

export const removeReplyResponseTransformer = async (data: any): Promise<RemoveReplyResponse> => {
    data = replyInfoSchemaResponseTransformer(data);
    return data;
};
