// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type GetProfileResponse = {
    /**
     * Account ID
     */
    id: string;
    username: string;
    bio: string;
    avatar: string;
};

export type UpdateProfileDto = {
    username: string;
    bio: string;
};

export type UpdateProfileResponse = {
    account_id: string;
    username: string;
    bio: string;
};

export type RegisterDto = {
    username: string;
    password: string;
    ident_type: 'Email';
    ident_value: string;
    /**
     * The mail / sms captcha.
     */
    captcha: string;
    /**
     * iff enable_invite flag true will required
     */
    invite_code: string;
};

export type CreateAccountResponse = {
    account_id: string;
};

export type RemoveAccountResponse = {
    account_id: string;
};

export type ResetPasswordDto = {
    ident_value: string;
    password: string;
    mfa_code: string;
};

export type UpdatePassword = {
    [key: string]: unknown;
};

export type LoginDto = {
    ident_type: 'Email';
    ident_value: string;
    cert_value: string;
};

export type LoginResponse = {
    /**
     * JWT,TTL: 15 Minutes. Used for accessing protected resources.
     */
    accessToken: string;
    /**
     * JWT, TTL: 1 Day. Used to request `/auth/refresh` refresh AccessToken
     */
    refreshToken: string;
};

export type CreatePostDto = {
    categoryId: string;
    title: string;
    content: string;
};

export type CreatePostResponse = {
    postId: string;
};

export type Pagination = {
    total: number;
    data: Array<string>;
};

export type ThreadAuthorSummary = {
    id: string;
    name: string;
    bio: string;
    avatar: string;
};

export type Thread = {
    id: string;
    author: ThreadAuthorSummary;
    content: string;
    createdAt: string;
};

export type CreateThread = {
    content: string;
};

export type CreateThreadResponse = {
    [key: string]: unknown;
};

export type AuthorSummary = {
    id: string;
    name: string;
    avatar?: string;
};

export type PostSummary = {
    id: string;
    title: string;
    content: string;
    author: AuthorSummary;
    createdAt: string;
};

export type HiddenPostDto = {
    [key: string]: unknown;
};

export type HiddenPostResponse = {
    [key: string]: unknown;
};

export type CursorPagination = {
    cursor: string;
    data: Array<string>;
    total: number;
};

export type CreateCategoryDto = {
    name: string;
    parent: string;
};

export type CreateCategoryResponse = {
    id: string;
    name: string;
    hasChildren: boolean;
    parent: string;
};

export type UpdateCategoryResponse = {
    id: string;
};

export type UpdateCategoryDto = {
    parent: {
        [key: string]: unknown;
    };
};

export type CategorySummary = {
    id: string;
    name: string;
    parentId: {
        [key: string]: unknown;
    };
    hasChildren: boolean;
};

export type AccountControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/profile';
};

export type AccountControllerGetProfileResponses = {
    200: GetProfileResponse;
};

export type AccountControllerGetProfileResponse = AccountControllerGetProfileResponses[keyof AccountControllerGetProfileResponses];

export type AccountControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/account/profile';
};

export type AccountControllerUpdateProfileResponses = {
    200: UpdateProfileResponse;
};

export type AccountControllerUpdateProfileResponse = AccountControllerUpdateProfileResponses[keyof AccountControllerUpdateProfileResponses];

export type AccountControllerGetAccountProfileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/account/profile/{id}';
};

export type AccountControllerGetAccountProfileResponses = {
    200: GetProfileResponse;
};

export type AccountControllerGetAccountProfileResponse = AccountControllerGetAccountProfileResponses[keyof AccountControllerGetAccountProfileResponses];

export type AccountControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/account/register';
};

export type AccountControllerRegisterResponses = {
    201: CreateAccountResponse;
};

export type AccountControllerRegisterResponse = AccountControllerRegisterResponses[keyof AccountControllerRegisterResponses];

export type AccountControllerDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type AccountControllerDeleteResponses = {
    200: RemoveAccountResponse;
};

export type AccountControllerDeleteResponse = AccountControllerDeleteResponses[keyof AccountControllerDeleteResponses];

export type AccountControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/account/reset-password';
};

export type AccountControllerResetPasswordResponses = {
    200: unknown;
};

export type AccountControllerUpdatePasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/account/password';
};

export type AccountControllerUpdatePasswordResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    /**
     * Login Account. Will retun TokenPair.
     */
    201: LoginResponse;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * Logout account. Extract accountID from AccessToken
     */
    200: unknown;
};

export type AuthControllerRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshTokenResponses = {
    /**
     * Refresh Token. It will return new TokenPair. Should put refreshToken on header.
     */
    201: LoginResponse;
};

export type AuthControllerRefreshTokenResponse = AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type PostControllerGetPostsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page size
         */
        size: number;
        /**
         * Previous post ID
         */
        preId?: string;
        /**
         * Category ID
         */
        category?: string;
    };
    url: '/posts';
};

export type PostControllerGetPostsResponses = {
    200: CursorPagination & {
        data?: Array<PostSummary>;
    };
};

export type PostControllerGetPostsResponse = PostControllerGetPostsResponses[keyof PostControllerGetPostsResponses];

export type PostControllerCreatePostData = {
    body: CreatePostDto;
    path?: never;
    query?: never;
    url: '/posts';
};

export type PostControllerCreatePostResponses = {
    /**
     * Create a new post
     */
    201: CreatePostResponse;
};

export type PostControllerCreatePostResponse = PostControllerCreatePostResponses[keyof PostControllerCreatePostResponses];

export type PostControllerGetThreadData = {
    body?: never;
    path: {
        /**
         * PostId
         */
        id: string;
    };
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size: number;
    };
    url: '/posts/{id}/thread';
};

export type PostControllerGetThreadResponses = {
    200: Pagination & {
        data?: Array<Thread>;
    };
};

export type PostControllerGetThreadResponse = PostControllerGetThreadResponses[keyof PostControllerGetThreadResponses];

export type PostControllerCreateThreadData = {
    body: CreateThread;
    path: {
        /**
         * PostId
         */
        id: string;
    };
    query?: never;
    url: '/posts/{id}/thread';
};

export type PostControllerCreateThreadResponses = {
    201: CreateThreadResponse;
};

export type PostControllerCreateThreadResponse = PostControllerCreateThreadResponses[keyof PostControllerCreateThreadResponses];

export type PostControllerGetPostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type PostControllerGetPostResponses = {
    /**
     * Get a post summary
     */
    200: PostSummary;
};

export type PostControllerGetPostResponse = PostControllerGetPostResponses[keyof PostControllerGetPostResponses];

export type PostControllerHidePostData = {
    body: HiddenPostDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type PostControllerHidePostResponses = {
    /**
     * Hide a post.
     */
    200: HiddenPostResponse;
};

export type PostControllerHidePostResponse = PostControllerHidePostResponses[keyof PostControllerHidePostResponses];

export type CategoryControllerListCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Parent category ID
         */
        parent?: string;
    };
    url: '/category';
};

export type CategoryControllerListCategoriesResponses = {
    200: Array<CategorySummary>;
};

export type CategoryControllerListCategoriesResponse = CategoryControllerListCategoriesResponses[keyof CategoryControllerListCategoriesResponses];

export type CategoryControllerCreateCategoryData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/category';
};

export type CategoryControllerCreateCategoryResponses = {
    201: CreateCategoryResponse;
};

export type CategoryControllerCreateCategoryResponse = CategoryControllerCreateCategoryResponses[keyof CategoryControllerCreateCategoryResponses];

export type CategoryControllerDeleteCategoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/category/{id}';
};

export type CategoryControllerDeleteCategoryResponses = {
    200: UpdateCategoryResponse;
};

export type CategoryControllerDeleteCategoryResponse = CategoryControllerDeleteCategoryResponses[keyof CategoryControllerDeleteCategoryResponses];

export type CategoryControllerUpdateCategoryData = {
    body: UpdateCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/category/{id}';
};

export type CategoryControllerUpdateCategoryResponses = {
    200: UpdateCategoryResponse;
};

export type CategoryControllerUpdateCategoryResponse = CategoryControllerUpdateCategoryResponses[keyof CategoryControllerUpdateCategoryResponses];
