// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type GetProfileResponse = {
    /**
     * Account ID
     */
    id: string;
    username: string;
    bio: string;
    avatar: string;
};

export type UpdateProfileDto = {
    username: string;
    bio: string;
};

export type UpdateProfileResponse = {
    account_id: string;
    username: string;
    bio: string;
};

export type RegisterDto = {
    username: string;
    password: string;
    ident_type: 'Email';
    ident_value: string;
    /**
     * The mail / sms captcha.
     */
    captcha: string;
    /**
     * iff enable_invite flag true will required
     */
    invite_code: string;
};

export type RegisterResponse = {
    account_id: string;
};

export type RemoveAccountResponse = {
    account_id: string;
};

export type ResetPasswordDto = {
    ident_value: string;
    password: string;
    mfa_code: string;
};

export type UpdatePassword = {
    [key: string]: unknown;
};

export type AvatarUploadDto = {
    file: Blob | File;
};

export type UpdateAvatarResponse = {
    [key: string]: unknown;
};

export type LoginDto = {
    ident_type: 'Email';
    ident_value: string;
    cert_value: string;
};

export type LoginResponse = {
    /**
     * JWT,TTL: 15 Minutes. Used for accessing protected resources.
     */
    accessToken: string;
    /**
     * JWT, TTL: 1 Day. Used to request `/auth/refresh` refresh AccessToken
     */
    refreshToken: string;
};

export type CreatePostDto = {
    categoryId: string;
    title: string;
    content: string;
};

export type CreatePostResponse = {
    postId: string;
};

export type UploadImageRequest = {
    file: Blob | File;
};

export type UploadImageResponse = {
    url: string;
};

export type UploadFileRequest = {
    file: Array<Blob | File>;
    cost: number;
    threadId: string;
};

export type UploadFileResponse = {
    urls: string;
};

export type UnlockedStateDto = {
    unlocked: true;
    url: string;
    fileName: string;
    mimeType: string;
};

export type LockedStateDto = {
    unlocked: false;
    cost: number;
    fileName: string;
    mimeType: string;
};

export type ListResourceResponse = {
    resources: Array<({
        unlocked: true;
    } & UnlockedStateDto) | ({
        unlocked: false;
    } & LockedStateDto)>;
};

export type Pagination = {
    total: number;
    data: Array<string>;
};

export type ThreadAuthorSummary = {
    id: string;
    name: string;
    bio: string;
    avatar: string;
};

export type Thread = {
    id: string;
    author: ThreadAuthorSummary;
    content: string;
    createdAt: string;
    floor: number;
};

export type CreateThread = {
    content: string;
};

export type CreateThreadResponse = {
    [key: string]: unknown;
};

export type AuthorSummary = {
    id: string;
    name: string;
    avatar?: string;
};

export type PostSummary = {
    id: string;
    title: string;
    content: string;
    author: AuthorSummary;
    createdAt: string;
};

export type HiddenPostDto = {
    reason: string;
    due: Date;
};

export type HiddenPostResponse = {
    [key: string]: unknown;
};

export type CursorPagination = {
    cursor: string;
    data: Array<string>;
    total: number;
};

export type CreateCategoryDto = {
    name: string;
    parent?: string;
};

export type CreateCategoryResponse = {
    id: string;
    name: string;
    hasChildren: boolean;
    parentId?: {
        [key: string]: unknown;
    } | null;
};

export type RemoveCategoryResponse = {
    id: string;
};

export type UpdateCategoryDto = {
    parent: {
        [key: string]: unknown;
    };
};

export type UpdateCategoryResponse = {
    id: string;
};

export type CategorySummary = {
    id: string;
    name: string;
    parentId?: {
        [key: string]: unknown;
    } | null;
    hasChildren: boolean;
};

export type ProposalSummary = {
    id: string;
    title: string;
    status: 'active' | 'passed' | 'rejected' | 'executed' | 'cancelled';
    yes: number;
    no: number;
    total: number;
    createdAt: string;
    endAt: string;
};

export type ProposalEntity = {
    id: string;
    title: string;
    content: string;
    /**
     * 支持方占比
     */
    yes: number;
    /**
     * 反对方占比
     */
    no: number;
};

export type CreateProposal = {
    content: string;
    workflows: Array<string>;
    title: string;
};

export type CreateProposalResponse = {
    id: string;
};

export type VoteComment = {
    [key: string]: unknown;
};

export type CreateVote = {
    content: string;
    action: 'yes' | 'no';
};

export type CreateVoteResponse = {
    voteId: string;
};

export type CreateProposalCommentDto = {
    content: string;
};

export type CreateProposalCommandResponse = {
    commentId: string;
};

export type CommentAuthor = {
    id: string;
    nick: string;
    avatar: string;
};

export type ProposalComment = {
    commentId: string;
    content: string;
    author: CommentAuthor;
    createdAt: Date;
    action: 'yes' | 'no';
};

export type ActionTotal = {
    value: number;
};

export type ActionInfo = {
    name: string;
    schema: {
        [key: string]: unknown;
    };
};

export type ActionList = {
    [key: string]: unknown;
};

export type UpdateActive = {
    active: boolean;
};

export type UpdateActiveResponse = {
    id: string;
};

export type CreatePermissionDto = {
    code: string;
    name: string;
};

export type CreatePermissionResponse = {
    id: string;
    code: string;
    name: string;
};

export type RemovePermission = {
    [key: string]: unknown;
};

export type RemovePermissionResponse = {
    [key: string]: unknown;
};

export type PermissionSummary = {
    [key: string]: unknown;
};

export type FindPermissionResponse = {
    id: string;
    code: string;
    name: string;
};

export type CreateRole = {
    [key: string]: unknown;
};

export type CreateRoleResponse = {
    [key: string]: unknown;
};

export type RemoveRoleResponse = {
    [key: string]: unknown;
};

export type UpdateRole = {
    [key: string]: unknown;
};

export type UpdateRoleResponse = {
    [key: string]: unknown;
};

export type RoleSummary = {
    [key: string]: unknown;
};

export type FindRoleResponse = {
    [key: string]: unknown;
};

export type GetBalanceResponse = {
    balance: string;
};

export type AppControllerGetAssetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type AppControllerGetAssetResponses = {
    200: unknown;
};

export type AccountControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/profile';
};

export type AccountControllerGetProfileResponses = {
    200: GetProfileResponse;
};

export type AccountControllerGetProfileResponse = AccountControllerGetProfileResponses[keyof AccountControllerGetProfileResponses];

export type AccountControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/account/profile';
};

export type AccountControllerUpdateProfileResponses = {
    200: UpdateProfileResponse;
};

export type AccountControllerUpdateProfileResponse = AccountControllerUpdateProfileResponses[keyof AccountControllerUpdateProfileResponses];

export type AccountControllerGetAccountProfileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/account/profile/{id}';
};

export type AccountControllerGetAccountProfileResponses = {
    200: GetProfileResponse;
};

export type AccountControllerGetAccountProfileResponse = AccountControllerGetAccountProfileResponses[keyof AccountControllerGetAccountProfileResponses];

export type AccountControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/account/register';
};

export type AccountControllerRegisterResponses = {
    201: RegisterResponse;
};

export type AccountControllerRegisterResponse = AccountControllerRegisterResponses[keyof AccountControllerRegisterResponses];

export type AccountControllerDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type AccountControllerDeleteResponses = {
    200: RemoveAccountResponse;
};

export type AccountControllerDeleteResponse = AccountControllerDeleteResponses[keyof AccountControllerDeleteResponses];

export type AccountControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/account/reset-password';
};

export type AccountControllerResetPasswordResponses = {
    200: unknown;
};

export type AccountControllerUpdatePasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/account/password';
};

export type AccountControllerUpdatePasswordResponses = {
    200: unknown;
};

export type AccountControllerUploadAvatarData = {
    body: AvatarUploadDto;
    path?: never;
    query?: never;
    url: '/account/avatar';
};

export type AccountControllerUploadAvatarResponses = {
    201: UpdateAvatarResponse;
};

export type AccountControllerUploadAvatarResponse = AccountControllerUploadAvatarResponses[keyof AccountControllerUploadAvatarResponses];

export type AccountControllerGetPermissionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/permission';
};

export type AccountControllerGetPermissionResponses = {
    200: Array<string>;
};

export type AccountControllerGetPermissionResponse = AccountControllerGetPermissionResponses[keyof AccountControllerGetPermissionResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    /**
     * Login Account. Will retun TokenPair.
     */
    201: LoginResponse;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * Logout account. Extract accountID from AccessToken
     */
    200: unknown;
};

export type AuthControllerRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshTokenResponses = {
    /**
     * Refresh Token. It will return new TokenPair. Should put refreshToken on header.
     */
    201: LoginResponse;
};

export type AuthControllerRefreshTokenResponse = AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type PostControllerGetPostsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page size
         */
        size: number;
        /**
         * Previous post ID
         */
        preId?: string;
        /**
         * Category ID
         */
        category?: string;
    };
    url: '/posts';
};

export type PostControllerGetPostsResponses = {
    200: CursorPagination & {
        data?: Array<PostSummary>;
    };
};

export type PostControllerGetPostsResponse = PostControllerGetPostsResponses[keyof PostControllerGetPostsResponses];

export type PostControllerCreatePostData = {
    body: CreatePostDto;
    path?: never;
    query?: never;
    url: '/posts';
};

export type PostControllerCreatePostResponses = {
    /**
     * Create a new post
     */
    201: CreatePostResponse;
};

export type PostControllerCreatePostResponse = PostControllerCreatePostResponses[keyof PostControllerCreatePostResponses];

export type PostControllerUploadImageData = {
    body: UploadImageRequest;
    path?: never;
    query?: never;
    url: '/posts/thread/image';
};

export type PostControllerUploadImageResponses = {
    200: UploadImageResponse;
};

export type PostControllerUploadImageResponse = PostControllerUploadImageResponses[keyof PostControllerUploadImageResponses];

export type PostControllerUploadResourceData = {
    body: UploadFileRequest;
    path?: never;
    query?: never;
    url: '/posts/thread/resource';
};

export type PostControllerUploadResourceResponses = {
    200: UploadFileResponse;
};

export type PostControllerUploadResourceResponse = PostControllerUploadResourceResponses[keyof PostControllerUploadResourceResponses];

export type PostControllerListResourcesData = {
    body?: never;
    path?: never;
    query: {
        'thread-id': string;
    };
    url: '/posts/{id}/resource';
};

export type PostControllerListResourcesResponses = {
    200: ListResourceResponse;
};

export type PostControllerListResourcesResponse = PostControllerListResourcesResponses[keyof PostControllerListResourcesResponses];

export type PostControllerGetThreadData = {
    body?: never;
    path: {
        /**
         * PostId
         */
        id: string;
    };
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size: number;
    };
    url: '/posts/{id}/thread';
};

export type PostControllerGetThreadResponses = {
    200: Pagination & {
        data?: Array<Thread>;
    };
};

export type PostControllerGetThreadResponse = PostControllerGetThreadResponses[keyof PostControllerGetThreadResponses];

export type PostControllerCreateThreadData = {
    body: CreateThread;
    path: {
        /**
         * PostId
         */
        id: string;
    };
    query?: never;
    url: '/posts/{id}/thread';
};

export type PostControllerCreateThreadResponses = {
    201: CreateThreadResponse;
};

export type PostControllerCreateThreadResponse = PostControllerCreateThreadResponses[keyof PostControllerCreateThreadResponses];

export type PostControllerGetPostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type PostControllerGetPostResponses = {
    /**
     * Get a post summary
     */
    200: PostSummary;
};

export type PostControllerGetPostResponse = PostControllerGetPostResponses[keyof PostControllerGetPostResponses];

export type PostControllerHidePostData = {
    body: HiddenPostDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type PostControllerHidePostResponses = {
    /**
     * Hide a post.
     */
    200: HiddenPostResponse;
};

export type PostControllerHidePostResponse = PostControllerHidePostResponses[keyof PostControllerHidePostResponses];

export type CategoryControllerListCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Parent category ID
         */
        parent?: string;
    };
    url: '/category';
};

export type CategoryControllerListCategoriesResponses = {
    200: Array<CategorySummary>;
};

export type CategoryControllerListCategoriesResponse = CategoryControllerListCategoriesResponses[keyof CategoryControllerListCategoriesResponses];

export type CategoryControllerCreateCategoryData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/category';
};

export type CategoryControllerCreateCategoryResponses = {
    201: CreateCategoryResponse;
};

export type CategoryControllerCreateCategoryResponse = CategoryControllerCreateCategoryResponses[keyof CategoryControllerCreateCategoryResponses];

export type CategoryControllerDeleteCategoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/category/{id}';
};

export type CategoryControllerDeleteCategoryResponses = {
    200: RemoveCategoryResponse;
};

export type CategoryControllerDeleteCategoryResponse = CategoryControllerDeleteCategoryResponses[keyof CategoryControllerDeleteCategoryResponses];

export type CategoryControllerUpdateCategoryData = {
    body: UpdateCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/category/{id}';
};

export type CategoryControllerUpdateCategoryResponses = {
    200: UpdateCategoryResponse;
};

export type CategoryControllerUpdateCategoryResponse = CategoryControllerUpdateCategoryResponses[keyof CategoryControllerUpdateCategoryResponses];

export type ProposalControllerListProposalData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 页码
         */
        page: number;
        /**
         * 每页数量
         */
        size: number;
    };
    url: '/proposal';
};

export type ProposalControllerListProposalResponses = {
    200: Pagination & {
        data?: Array<ProposalSummary>;
    };
};

export type ProposalControllerListProposalResponse = ProposalControllerListProposalResponses[keyof ProposalControllerListProposalResponses];

export type ProposalControllerCreateProposalData = {
    body: CreateProposal;
    path?: never;
    query?: never;
    url: '/proposal';
};

export type ProposalControllerCreateProposalResponses = {
    201: CreateProposalResponse;
};

export type ProposalControllerCreateProposalResponse = ProposalControllerCreateProposalResponses[keyof ProposalControllerCreateProposalResponses];

export type ProposalControllerGetProposalData = {
    body?: never;
    path: {
        /**
         * 提案ID
         */
        id: string;
    };
    query?: never;
    url: '/proposal/{id}';
};

export type ProposalControllerGetProposalResponses = {
    200: ProposalEntity;
};

export type ProposalControllerGetProposalResponse = ProposalControllerGetProposalResponses[keyof ProposalControllerGetProposalResponses];

export type ProposalControllerGetProposalVotesData = {
    body?: never;
    path: {
        /**
         * 提案ID
         */
        id: string;
    };
    query: {
        page: number;
        size: number;
    };
    url: '/proposal/{id}/votes';
};

export type ProposalControllerGetProposalVotesResponses = {
    200: Pagination;
};

export type ProposalControllerGetProposalVotesResponse = ProposalControllerGetProposalVotesResponses[keyof ProposalControllerGetProposalVotesResponses];

export type ProposalControllerVoteProposalData = {
    body: CreateVote;
    path: {
        id: string;
    };
    query?: never;
    url: '/proposal/{id}/vote';
};

export type ProposalControllerVoteProposalResponses = {
    201: CreateVoteResponse;
};

export type ProposalControllerVoteProposalResponse = ProposalControllerVoteProposalResponses[keyof ProposalControllerVoteProposalResponses];

export type ProposalControllerCreateProposalCommentData = {
    body: CreateProposalCommentDto;
    path: {
        /**
         * 提案ID
         */
        id: string;
    };
    query?: never;
    url: '/proposal/{id}/comment';
};

export type ProposalControllerCreateProposalCommentResponses = {
    201: CreateProposalCommandResponse;
};

export type ProposalControllerCreateProposalCommentResponse = ProposalControllerCreateProposalCommentResponses[keyof ProposalControllerCreateProposalCommentResponses];

export type ProposalControllerListProposalCommentsData = {
    body?: never;
    path: {
        /**
         * 提案ID
         */
        id: string;
    };
    query: {
        /**
         * 页码
         */
        page: number;
        /**
         * 每页数量
         */
        size: number;
    };
    url: '/proposal/{id}/comments';
};

export type ProposalControllerListProposalCommentsResponses = {
    200: Pagination & {
        data?: Array<ProposalComment>;
    };
};

export type ProposalControllerListProposalCommentsResponse = ProposalControllerListProposalCommentsResponses[keyof ProposalControllerListProposalCommentsResponses];

export type ActionControllerGetActionTotalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/action/total';
};

export type ActionControllerGetActionTotalResponses = {
    200: ActionTotal;
};

export type ActionControllerGetActionTotalResponse = ActionControllerGetActionTotalResponses[keyof ActionControllerGetActionTotalResponses];

export type ActionControllerGetActionInfoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/action/{id}';
};

export type ActionControllerGetActionInfoResponses = {
    200: ActionInfo;
};

export type ActionControllerGetActionInfoResponse = ActionControllerGetActionInfoResponses[keyof ActionControllerGetActionInfoResponses];

export type ActionControllerUpdateActiveData = {
    body: UpdateActive;
    path: {
        id: string;
    };
    query?: never;
    url: '/action/{id}';
};

export type ActionControllerUpdateActiveResponses = {
    200: UpdateActiveResponse;
};

export type ActionControllerUpdateActiveResponse = ActionControllerUpdateActiveResponses[keyof ActionControllerUpdateActiveResponses];

export type ActionControllerListActionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/action';
};

export type ActionControllerListActionResponses = {
    200: ActionList;
};

export type ActionControllerListActionResponse = ActionControllerListActionResponses[keyof ActionControllerListActionResponses];

export type PermissionControllerRemovePermissionData = {
    body: RemovePermission;
    path?: never;
    query?: never;
    url: '/permission';
};

export type PermissionControllerRemovePermissionResponses = {
    200: RemovePermissionResponse;
};

export type PermissionControllerRemovePermissionResponse = PermissionControllerRemovePermissionResponses[keyof PermissionControllerRemovePermissionResponses];

export type PermissionControllerListPermissionData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        size: number;
    };
    url: '/permission';
};

export type PermissionControllerListPermissionResponses = {
    200: Pagination & {
        data?: Array<PermissionSummary>;
    };
};

export type PermissionControllerListPermissionResponse = PermissionControllerListPermissionResponses[keyof PermissionControllerListPermissionResponses];

export type PermissionControllerCreatePermissionData = {
    body: CreatePermissionDto;
    path?: never;
    query?: never;
    url: '/permission';
};

export type PermissionControllerCreatePermissionResponses = {
    201: CreatePermissionResponse;
};

export type PermissionControllerCreatePermissionResponse = PermissionControllerCreatePermissionResponses[keyof PermissionControllerCreatePermissionResponses];

export type PermissionControllerFindPermissionData = {
    body?: never;
    path: {
        code: string;
    };
    query?: never;
    url: '/permission/{code}';
};

export type PermissionControllerFindPermissionResponses = {
    200: FindPermissionResponse;
};

export type PermissionControllerFindPermissionResponse = PermissionControllerFindPermissionResponses[keyof PermissionControllerFindPermissionResponses];

export type RoleControllerListRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/role';
};

export type RoleControllerListRoleResponses = {
    200: Pagination & {
        data?: Array<RoleSummary>;
    };
};

export type RoleControllerListRoleResponse = RoleControllerListRoleResponses[keyof RoleControllerListRoleResponses];

export type RoleControllerCreateRoleData = {
    body: CreateRole;
    path?: never;
    query?: never;
    url: '/role';
};

export type RoleControllerCreateRoleResponses = {
    201: CreateRoleResponse;
};

export type RoleControllerCreateRoleResponse = RoleControllerCreateRoleResponses[keyof RoleControllerCreateRoleResponses];

export type RoleControllerRemoveRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/role/{id}';
};

export type RoleControllerRemoveRoleResponses = {
    200: RemoveRoleResponse;
};

export type RoleControllerRemoveRoleResponse = RoleControllerRemoveRoleResponses[keyof RoleControllerRemoveRoleResponses];

export type RoleControllerUpdateRoleData = {
    body: UpdateRole;
    path?: never;
    query?: never;
    url: '/role/{id}';
};

export type RoleControllerUpdateRoleResponses = {
    200: UpdateRoleResponse;
};

export type RoleControllerUpdateRoleResponse = RoleControllerUpdateRoleResponses[keyof RoleControllerUpdateRoleResponses];

export type RoleControllerFindRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/role/{code}';
};

export type RoleControllerFindRoleResponses = {
    200: FindRoleResponse;
};

export type RoleControllerFindRoleResponse = RoleControllerFindRoleResponses[keyof RoleControllerFindRoleResponses];

export type WalletControllerGetBalanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wallet/balance';
};

export type WalletControllerGetBalanceResponses = {
    200: GetBalanceResponse;
};

export type WalletControllerGetBalanceResponse = WalletControllerGetBalanceResponses[keyof WalletControllerGetBalanceResponses];

export type WalletControllerListTranscationData = {
    body?: never;
    path?: never;
    query: {
        year: number;
    };
    url: '/wallet/transcation';
};

export type WalletControllerListTranscationResponses = {
    200: unknown;
};
