// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type LoginDto = {
    /**
     * 标识类型
     */
    identType: string;
    /**
     * 标识值
     */
    identValue: string;
    /**
     * 凭证类型
     */
    credentialType: string;
    /**
     * 凭证值
     */
    credentialValue: string;
};

export type TokenPair = {
    /**
     * 访问令牌, 用于访问受到保护的资源
     */
    accessToken: string;
    /**
     * 刷新令牌, 用于刷新访问令牌
     */
    refreshToken: string;
    /**
     * 访问令牌有效期 (秒)
     */
    accessTokenTTL: number;
    /**
     * 刷新令牌有效期 (秒)
     */
    refreshTokenTTL: number;
};

export type RegisterProfile = {
    /**
     * 昵称
     */
    nick: string;
    /**
     * 个人简介
     */
    bio: string;
};

export type RegisterRequest = {
    /**
     * 标识类型
     */
    identType: string;
    /**
     * 标识值
     */
    identValue: string;
    /**
     * 凭证类型
     */
    credentialType: string;
    /**
     * 凭证值
     */
    credentialValue: string;
    /**
     * 个人信息
     */
    profile: RegisterProfile;
    /**
     * 验证码
     */
    verificationCode?: string;
};

export type RegisterResponse = {
    /**
     * 账号ID
     */
    accountId: {
        [key: string]: unknown;
    };
};

export type RefreshTokenDto = {
    /**
     * 刷新令牌
     */
    token: string;
};

export type PaginationData = {
    /**
     * 数据列表
     */
    data: Array<string>;
    /**
     * 总条数
     */
    total: number;
};

export type CategoryInfo = {
    /**
     * 分类ID
     */
    id: {
        [key: string]: unknown;
    };
    /**
     * 分类名称
     */
    name: string;
    /**
     * 分类图标
     */
    icon: string;
    /**
     * 分类颜色
     */
    color: string;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * 是否置顶
     */
    pined: boolean;
};

export type CreateCategoryRequest = {
    /**
     * 分类名称
     */
    name: string;
    /**
     * 分类颜色, 十六进制色彩值
     */
    color?: string;
    /**
     * 分类图标, 图标class
     */
    icon?: string;
    /**
     * 是否置顶
     */
    pin?: boolean;
};

export type UpdateCategoryRequest = {
    /**
     * 分类名称
     */
    name?: string;
    /**
     * 分类颜色, 十六进制色彩值
     */
    color?: string;
    /**
     * 分类图标, 图标class
     */
    icon?: string;
    /**
     * 是否置顶
     */
    pin?: boolean;
};

export type RemoveCategoryResponse = {
    id: string;
};

export type ReplyAuthor = {
    /**
     * 回复作者ID
     */
    id: {
        [key: string]: unknown;
    };
    /**
     * 回复作者昵称
     */
    nick: string;
};

export type ReplyItem = {
    /**
     * 回复ID
     */
    id: {
        [key: string]: unknown;
    };
    /**
     * 回复内容
     */
    content: string;
    /**
     * 回复作者
     */
    author: ReplyAuthor;
    /**
     * 回复创建时间
     */
    createdAt: string;
};

export type TopicAuthor = {
    /**
     * 主题作者ID
     */
    id: string;
    /**
     * 主题作者昵称
     */
    nick: string;
};

export type TopicInfo = {
    /**
     * 主题ID
     */
    id: string;
    /**
     * 主题标题
     */
    title: string;
    /**
     * 主题内容
     */
    content: string;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * 分类
     */
    category: TopicCategory;
    /**
     * 回复总数
     */
    repliesTotal: number;
};

export type CreateReplyDto = {
    /**
     * 回复内容
     */
    content: string;
};

export type ReplyInfo = {
    /**
     * 回复ID
     */
    id: {
        [key: string]: unknown;
    };
    /**
     * 回复内容
     */
    content: string;
    /**
     * 回复作者
     */
    author: ReplyAuthor;
    /**
     * 回复创建时间
     */
    createdAt: Date;
};

export type CreateTopicDto = {
    /**
     * 主题标题
     */
    title: string;
    /**
     * 主题内容
     */
    content: string;
    /**
     * 是否置顶
     */
    pinned: boolean;
};

export type UpdateTopicDto = {
    /**
     * 主题标题
     */
    title: string;
    /**
     * 主题内容
     */
    content: string;
    /**
     * 是否置顶
     */
    pinned: boolean;
    /**
     * 分类ID
     */
    categoryId: {
        [key: string]: unknown;
    };
};

export type UpdateTopicResponse = {
    /**
     * 主题ID
     */
    id: string;
};

export type ProfileInfo = {
    /**
     * 用户ID
     */
    id: {
        [key: string]: unknown;
    };
    /**
     * 昵称
     */
    nick: string;
    /**
     * 个人简介
     */
    bio?: string;
};

export type TopicCategory = {
    /**
     * 分类ID
     */
    id: string;
    /**
     * 分类名称
     */
    name: string;
    /**
     * 分类颜色
     */
    color: string;
};

export type UpdateProfile = {
    /**
     * 昵称
     */
    nick: string;
    /**
     * 个人简介
     */
    bio: string;
};

export type HttpPresentationError = {
    /**
     * 错误 message
     */
    message: string;
    /**
     * 错误状态码
     */
    statusCode: number;
    /**
     * 错误详情
     */
    details: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginResponses = {
    201: TokenPair;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterResponses = {
    201: RegisterResponse;
};

export type RegisterResponse2 = RegisterResponses[keyof RegisterResponses];

export type RefreshTokenData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh-token';
};

export type RefreshTokenResponses = {
    201: TokenPair;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type ListCategoryData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 页码
         */
        page: number;
        /**
         * 每页数量
         */
        size: number;
    };
    url: '/category';
};

export type ListCategoryResponses = {
    /**
     * 获取分类列表
     */
    200: PaginationData & {
        data?: Array<CategoryInfo>;
    };
};

export type ListCategoryResponse = ListCategoryResponses[keyof ListCategoryResponses];

export type CreateCategoryData = {
    body: CreateCategoryRequest;
    path?: never;
    query?: never;
    url: '/category';
};

export type CreateCategoryResponses = {
    /**
     * 创建分类
     */
    200: CategoryInfo;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type RemoveCategoryData = {
    body?: never;
    path: {
        /**
         * 分类ID
         */
        id: unknown;
    };
    query?: never;
    url: '/category/{id}';
};

export type RemoveCategoryResponses = {
    /**
     * 删除分类
     */
    200: RemoveCategoryResponse;
};

export type RemoveCategoryResponse2 = RemoveCategoryResponses[keyof RemoveCategoryResponses];

export type FindCategoryData = {
    body?: never;
    path: {
        /**
         * 分类ID
         */
        id: unknown;
    };
    query?: never;
    url: '/category/{id}';
};

export type FindCategoryResponses = {
    /**
     * 获取分类详情
     */
    200: CategoryInfo;
};

export type FindCategoryResponse = FindCategoryResponses[keyof FindCategoryResponses];

export type UpdateCategoryData = {
    body: UpdateCategoryRequest;
    path: {
        /**
         * 分类ID
         */
        id: unknown;
    };
    query?: never;
    url: '/category/{id}';
};

export type UpdateCategoryResponses = {
    /**
     * 更新分类
     */
    200: CategoryInfo;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type RecoverCategoryData = {
    body?: never;
    path: {
        /**
         * 分类ID
         */
        id: unknown;
    };
    query?: never;
    url: '/category/recover/{id}';
};

export type RecoverCategoryResponses = {
    /**
     * 恢复分类
     */
    200: CategoryInfo;
};

export type RecoverCategoryResponse = RecoverCategoryResponses[keyof RecoverCategoryResponses];

export type ListReplyData = {
    body?: never;
    path: {
        /**
         * 主题ID
         */
        topicId: string;
    };
    query: {
        /**
         * 页码
         */
        page: number;
        /**
         * 每页数量
         */
        size: number;
    };
    url: '/topic/replies/{topicId}';
};

export type ListReplyResponses = {
    200: PaginationData & {
        data?: Array<ReplyItem>;
    };
};

export type ListReplyResponse = ListReplyResponses[keyof ListReplyResponses];

export type CreateReplyData = {
    body: CreateReplyDto;
    path: {
        /**
         * 主题ID
         */
        topicId: string;
    };
    query?: never;
    url: '/topic/replies/{topicId}';
};

export type CreateReplyResponses = {
    201: ReplyInfo;
};

export type CreateReplyResponse = CreateReplyResponses[keyof CreateReplyResponses];

export type ListTopicData = {
    body?: never;
    path: {
        /**
         * 分类ID
         */
        categoryId: unknown;
    };
    query: {
        /**
         * 页码
         */
        page: number;
        /**
         * 每页数量
         */
        size: number;
    };
    url: '/topic/{categoryId}';
};

export type ListTopicResponses = {
    200: PaginationData & {
        data?: Array<TopicInfo>;
    };
};

export type ListTopicResponse = ListTopicResponses[keyof ListTopicResponses];

export type CreateTopicData = {
    body: CreateTopicDto;
    path: {
        /**
         * 分类ID
         */
        categoryId: unknown;
    };
    query?: never;
    url: '/topic/{categoryId}';
};

export type CreateTopicResponses = {
    201: TopicInfo;
};

export type CreateTopicResponse = CreateTopicResponses[keyof CreateTopicResponses];

export type RemoveReplyData = {
    body?: never;
    path: {
        /**
         * 回复ID
         */
        replyId: unknown;
    };
    query?: never;
    url: '/topic/replies/{replyId}';
};

export type RemoveReplyResponses = {
    200: ReplyInfo;
};

export type RemoveReplyResponse = RemoveReplyResponses[keyof RemoveReplyResponses];

export type RemoveTopicData = {
    body?: never;
    path: {
        /**
         * 主题ID
         */
        topicId: string;
    };
    query?: never;
    url: '/topic/{topicId}';
};

export type RemoveTopicResponses = {
    200: TopicInfo;
};

export type RemoveTopicResponse = RemoveTopicResponses[keyof RemoveTopicResponses];

export type UpdateTopicData = {
    body: UpdateTopicDto;
    path: {
        /**
         * 主题ID
         */
        topicId: string;
    };
    query?: never;
    url: '/topic/{topicId}';
};

export type UpdateTopicResponses = {
    200: UpdateTopicResponse;
};

export type UpdateTopicResponse2 = UpdateTopicResponses[keyof UpdateTopicResponses];

export type GetProfileData = {
    body?: never;
    path?: {
        /**
         * Account ID
         */
        id?: unknown;
    };
    query?: never;
    url: '/profile/{id}';
};

export type GetProfileResponses = {
    200: ProfileInfo;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetPublishedTopicData = {
    body?: never;
    path: {
        /**
         * Account ID
         */
        id: unknown;
    };
    query: {
        /**
         * Page number
         */
        page: number;
        /**
         * Page size
         */
        size: number;
    };
    url: '/profile/{id}/published-topic';
};

export type GetPublishedTopicResponses = {
    200: PaginationData & {
        data?: Array<TopicInfo>;
    };
};

export type GetPublishedTopicResponse = GetPublishedTopicResponses[keyof GetPublishedTopicResponses];

export type UpdateProfileData = {
    body: UpdateProfile;
    path?: never;
    query?: never;
    url: '/profile';
};

export type UpdateProfileResponses = {
    200: unknown;
};
