/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "INTERNAL_ERROR": string;
        "USER_EXISTS": string;
        "VERFICATION_CODE_REPEAT_SEND": string;
    };
    "mail": {
        "register": {
            "title": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
