/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "INTERNAL_ERROR": string;
        "UNAUTHORIZED": string;
        "INVALID_TOKEN": string;
        "TOKEN_EXPIRED": string;
        "USER_EXISTS": string;
        "USER_NOT_FOUND": string;
        "VERIFICATION_CODE_REPEAT_SEND": string;
        "VERIFICATION_CODE_NOT_FOUND_OR_EXPIRED": string;
        "TEMPLATE_NOT_FOUND": string;
        "TEMPLATE_CAN_NOT_OPEN": string;
        "PASSWORD_INCORRECT": string;
        "CATEGORY_NOT_FOUND": string;
    };
    "mail": {
        "register": {
            "title": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
