//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "badge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    pub required_points: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_badge::Entity")]
    UserBadge,
}

impl Related<super::user_badge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserBadge.def()
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_badge::Relation::Account.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_badge::Relation::Badge.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
