//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod account;
pub mod badge;
pub mod cert;
pub mod dictator;
pub mod identity;
pub mod post;
pub mod post_tag;
pub mod profile;
pub mod proposal;
pub mod proposal_comment;
pub mod ruling;
pub mod shop_item;
pub mod tag;
pub mod thread;
pub mod thread_comment;
pub mod token;
pub mod user_badge;
pub mod user_inventory;
pub mod vote;
