//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::account::Entity as Account;
pub use super::badge::Entity as Badge;
pub use super::cert::Entity as Cert;
pub use super::dictator::Entity as Dictator;
pub use super::identity::Entity as Identity;
pub use super::post::Entity as Post;
pub use super::post_tag::Entity as PostTag;
pub use super::profile::Entity as Profile;
pub use super::proposal::Entity as Proposal;
pub use super::proposal_comment::Entity as ProposalComment;
pub use super::ruling::Entity as Ruling;
pub use super::shop_item::Entity as ShopItem;
pub use super::tag::Entity as Tag;
pub use super::thread::Entity as Thread;
pub use super::thread_comment::Entity as ThreadComment;
pub use super::token::Entity as Token;
pub use super::user_badge::Entity as UserBadge;
pub use super::user_inventory::Entity as UserInventory;
pub use super::vote::Entity as Vote;
