//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shop_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub price: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub item_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_inventory::Entity")]
    UserInventory,
}

impl Related<super::user_inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserInventory.def()
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_inventory::Relation::Account.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_inventory::Relation::ShopItem.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
