name: E2E Test
on:
  pull_request:
    branches:
      - dev
    paths:
      - 'packages/water-bbs-api/**'
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'packages/water-bbs-api/**'
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:22-alpine
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm i -g pnpm && pnpm i --dangerously-allow-all-builds
      - name: Connect to Redis
        run: pnpm test:api-e2e
